// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, name, gender, gender_probability, sample_size, age,age_group, country_id, country_probability, created_at )
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    NOW()
)RETURNING id, name, gender, gender_probability, sample_size, age, age_group, country_id, country_probability, created_at
`

type CreateUserParams struct {
	ID                 uuid.UUID
	Name               string
	Gender             string
	GenderProbability  float64
	SampleSize         int32
	Age                int32
	AgeGroup           string
	CountryID          string
	CountryProbability float64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.GenderProbability,
		arg.SampleSize,
		arg.Age,
		arg.AgeGroup,
		arg.CountryID,
		arg.CountryProbability,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.SampleSize,
		&i.Age,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
 SELECT id, name, gender, gender_probability, sample_size, age, age_group, country_id, country_probability, created_at FROM users
WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.SampleSize,
		&i.Age,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
	)
	return i, err
}
