// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID                 uuid.UUID
	Name               string
	Gender             string
	GenderProbability  float64
	SampleSize         int32
	Age                int32
	AgeGroup           string
	CountryID          string
	CountryProbability float64
	CreatedAt          sql.NullTime
}
